/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author hogar
 */
public class Administrador extends javax.swing.JFrame {
    
    String usuar,nombre_usuario;
    
    public static int sesion_usuario;

    
    public Administrador() {
        initComponents();
        
        usuar=Login.user;
        sesion_usuario=1;
        
        
        setSize(650,430);
        setResizable(false);
        setTitle("Administrador - Sesion de "+usuar);
        setLocationRelativeTo(null);
        
        /*Metodo para que el programa no siga en funcionamiento
        cuando se cierre la ventana
        */
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(Label_wallAdm.getWidth(), Label_wallAdm.getHeight(), Image.SCALE_DEFAULT));
        Label_wallAdm.setIcon(icono);
        this.repaint();
        
        try{
            Conexion c=new Conexion();
            ResultSet rs=c.consulta("select nombre_usuario from usuarios where username = \""+usuar+"\"");
            if(rs.next()){
                nombre_usuario = rs.getString("nombre_usuario");
                Label_nameuser.setText(nombre_usuario);
            }
        }catch (Exception e){
            System.err.println("Error al consultar nombre de administrador");
        }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logtitle.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_nameuser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Boton_registrarUser = new javax.swing.JButton();
        Boton_gestionUsers = new javax.swing.JButton();
        Boton_creatividad = new javax.swing.JButton();
        Boton_capturista = new javax.swing.JButton();
        Boton_tecnico = new javax.swing.JButton();
        Boton_Acercade = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Label_wallAdm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nameuser.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Label_nameuser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Label_nameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestionar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creatividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Panel Vista Capturista");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Panel Vista Tecnico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 340, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acerca De");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        Boton_registrarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        Boton_registrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_registrarUserActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_registrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        Boton_gestionUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        Boton_gestionUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_gestionUsersActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_gestionUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 100));

        Boton_creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        Boton_creatividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_creatividadActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 120, 100));

        Boton_capturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        Boton_capturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_capturistaActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 100));

        Boton_tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tecnico.png"))); // NOI18N
        Boton_tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_tecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 100));

        Boton_Acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geekipedia.png"))); // NOI18N
        Boton_Acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AcercadeActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 120, 100));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Creado por Cyan Lewwit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 380, -1, -1));
        getContentPane().add(Label_wallAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_registrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_registrarUserActionPerformed

        Registrar_usuarios rs=new Registrar_usuarios();
        rs.setVisible(true);
    }//GEN-LAST:event_Boton_registrarUserActionPerformed

    private void Boton_gestionUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_gestionUsersActionPerformed
        // TODO add your handling code here:
        Gestionar_Usuarios gu=new Gestionar_Usuarios();
        gu.setVisible(true);
    }//GEN-LAST:event_Boton_gestionUsersActionPerformed

    private void Boton_creatividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_creatividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_creatividadActionPerformed

    private void Boton_capturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_capturistaActionPerformed
        try {
            // TODO add your handling code here:
            Capturista cap=new Capturista();
            cap.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Boton_capturistaActionPerformed

    private void Boton_tecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_tecnicoActionPerformed
        
        Tecnico t;
        try {
            t = new Tecnico();
            t.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Boton_tecnicoActionPerformed

    private void Boton_AcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AcercadeActionPerformed
        try {
            // TODO add your handling code here:
            AcercaDe DE =new AcercaDe();
            DE.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Boton_AcercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Acercade;
    private javax.swing.JButton Boton_capturista;
    private javax.swing.JButton Boton_creatividad;
    private javax.swing.JButton Boton_gestionUsers;
    private javax.swing.JButton Boton_registrarUser;
    private javax.swing.JButton Boton_tecnico;
    private javax.swing.JLabel Label_nameuser;
    private javax.swing.JLabel Label_wallAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
